services:
  api:
    build:
      context: .
      dockerfile: src/EasyLotteryAPI/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      Storage__Directory: /data
    ports:
      - "18930:18930"
    volumes:
      - easy_lottery_data:/data

volumes:
  easy_lottery_data:
